kind: NetworkPolicy
apiVersion: extensions/v1beta1 
metadata:
  name: allow-frontend
  namespace: default
spec:
  podSelector:            
    matchLabels:
      role: backend
  ingress:                
    - from:              
        - namespaceSelector:
            matchLabels:
      ports:
        - protocol: TCP
          port: 6379
        - protocol: UDP
          port: 6378
